{"name": "Проверка ответа на запрос аутентификации с неверным паролем", "status": "passed", "start": 1719119527719, "stop": 1719119528046, "uuid": "1eea3b2a-9338-4bed-96b8-50a129438aec", "historyId": "7b59ea21293aa51d8fb438826b986f6c", "testCaseId": "7b59ea21293aa51d8fb438826b986f6c", "fullName": "tests.test_authentication.TestAuthentication#test_auth_with_wrong_passwd_expected_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_authentication"}, {"name": "subSuite", "value": "TestAuthentication"}, {"name": "host", "value": "LAPTOP-0911SMBB"}, {"name": "thread", "value": "16156-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_authentication"}]}