{"name": "Проверка ответа на запрос аутентификации с неверным паролем", "status": "passed", "start": 1718506677305, "stop": 1718506677468, "uuid": "0e5abfdd-4327-4a72-9422-5a9dcaa79dcc", "historyId": "7b59ea21293aa51d8fb438826b986f6c", "testCaseId": "7b59ea21293aa51d8fb438826b986f6c", "fullName": "tests.test_authentication.TestAuthentication#test_auth_with_wrong_passwd_expected_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_authentication"}, {"name": "subSuite", "value": "TestAuthentication"}, {"name": "host", "value": "LAPTOP-0911SMBB"}, {"name": "thread", "value": "3752-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_authentication"}]}